pipeline {
    agent any
    parameters {

        choice(choices: 'no\nyes', description: 'Enable o-profile', name: 'enable_oprofile')
        choice(choices: 'no\nyes', description: 'Are you sure you want to execute this test?', name: 'run_test_only')
        string(defaultValue: "test.feature", description: 'Feature file', name: 'feature_file')
        string(defaultValue: "@test1", description: 'cucumber test tag', name: 'tag')
        string(defaultValue: "msuarez@redhat.com", description: 'email for notifications', name: 'notification_email')

    }

    environment {
        node= '1.1.1.1'
        oprofile_report_name= 'report.txt'

    }

    stages {

        stage('Test'){
            when {
                environment name: 'run_test_only', value: 'no'
            }
            steps{
                sh 'cd examples/java-calculator && mvn clean integration-test'
            }
        }

        stage ('Run Performance test') {
        steps {
        parallel(
        "Start oprofile":
          {
            script{

                  if (env.enable_oprofile =='yes')
                  {
                 }
                 else
                 echo "oprofile was not enabled"

            }

        },

        "Execute test":{
                echo "Run performance test. Feature file: ${feature_file} Tag: ${tag} "
                //sh "cucumber ${feature_file}' -t '${tag}' -b -x -v --format html --out reports.html --format pretty"
             }

        )

        }
        }


    }

    post {
        success {
        //node('node1'){

            echo "Test succeeded"
            script {

                mail(bcc: '',
                     body: "Run ${JOB_NAME}-#${BUILD_NUMBER} succeeded. To get more details, visit the build results page: ${BUILD_URL}.",
                     cc: '',
                     from: 'jenkins-admin@gmail.com',
                     replyTo: '',
                     subject: "${JOB_NAME} ${BUILD_NUMBER} succeeded",
                     to: env.notification_email)
                if (env.enable_oprofile =='yes')
                     {
                        //archiveArtifacts artifacts: "${analyzed_component}-${oprofile_report_name}"
                      }
                      cucumber fileIncludePattern: '**/java-calculator/target/cucumber-report.json', sortingMethod: 'ALPHABETICAL'
            //publishHTML([allowMissing: false, alwaysLinkToLastBuild: false, keepAll: true, reportDir: '/home/reports', reportFiles: 'reports.html', reportName: 'Performance Test Report', reportTitles: ''])
            }
        //}
        }
        failure {
            echo "Test failed"
            mail(bcc: '',
                body: "Run ${JOB_NAME}-#${BUILD_NUMBER} succeeded. To get more details, visit the build results page: ${BUILD_URL}.",
                 cc: '',
                 from: 'jenkins-admin@gmail.com',
                 replyTo: '',
                 subject: "${JOB_NAME} ${BUILD_NUMBER} failed",
                 to: env.notification_email)
                 cucumber fileIncludePattern: '**/java-calculator/target/cucumber-report.json', sortingMethod: 'ALPHABETICAL'
            //publishHTML([allowMissing: true, alwaysLinkToLastBuild: false, keepAll: true, reportDir: '/home/tester/reports', reportFiles: 'reports.html', reportName: 'Performance Test Report', reportTitles: ''])
        }
    }

}
